version: 2
updates:
  # Dart pub packages
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
      day: monday
    assignees:
      - rania-run
    labels:
      - "chore: deps"
    commit-message:
      prefix: "chore(deps)"

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    assignees:
      - rania-run
    labels:
      - "chore: deps"
    commit-message:
      prefix: "chore(deps)"
